/**
 * CameraFTP - A Cross-platform FTP companion for camera photo transfer
 * Copyright (C) 2026 GoldJohnKing <GoldJohnKing@Live.cn>
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/**
 * TypeScript type definitions
 *
 * Most types are auto-generated by ts-rs from Rust structs.
 * Run `cargo run --bin export-bindings` in src-tauri to regenerate bindings.
 */

// ===== Re-export from ts-rs generated bindings =====
export type { ServerInfo } from '../../src-tauri/bindings/ServerInfo';
export type { ServerStateSnapshot } from '../../src-tauri/bindings/ServerStateSnapshot';
export type { ServerRuntimeView } from '../../src-tauri/bindings/ServerRuntimeView';
export type { AdvancedConnectionConfig } from '../../src-tauri/bindings/AdvancedConnectionConfig';
export type { AppConfig } from '../../src-tauri/bindings/AppConfig';
export type { StorageInfo } from '../../src-tauri/bindings/StorageInfo';
export type { PermissionStatus } from '../../src-tauri/bindings/PermissionStatus';
export type { ServerStartCheckResult } from '../../src-tauri/bindings/ServerStartCheckResult';
export type { ExifInfo } from '../../src-tauri/bindings/ExifInfo';
export type { FileInfo } from '../../src-tauri/bindings/FileInfo';
export type { PreviewWindowConfig } from '../../src-tauri/bindings/PreviewWindowConfig';
export type { AndroidImageOpenMethod } from '../../src-tauri/bindings/AndroidImageOpenMethod';

// ===== Re-export from global.ts =====
export * from './global';

// ===== Re-export from gallery-v2.ts =====
export type { MediaItemDto, MediaCursor, MediaPageRequest, MediaPageResponse, ThumbRequest, ThumbResult, ThumbResultListener } from './gallery-v2';

// ===== Re-export from events.ts =====
export type { ConfigChangedEvent } from './events';
