// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConfig } from "./ProviderConfig";

/**
 * AI修图总配置
 */
export type AiEditConfig = { 
/**
 * 总开关
 */
enabled: boolean, 
/**
 * 接收图片后自动触发
 */
autoEdit: boolean, 
/**
 * 自动修图提示词
 */
prompt: string, 
/**
 * 手动修图上次使用的提示词
 */
manualPrompt: string, 
/**
 * 手动修图上次使用的模型（空则使用 provider.model）
 */
manualModel: string, 
/**
 * Provider 配置
 */
provider: ProviderConfig, };
