// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConfig } from "./ProviderConfig";

/**
 * AI修图总配置
 */
export type AiEditConfig = { 
/**
 * 总开关
 */
enabled: boolean, 
/**
 * 接收图片后自动触发
 */
autoEdit: boolean, 
/**
 * 预设提示词
 */
prompt: string, 
/**
 * Provider 配置
 */
provider: ProviderConfig, };
