// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeedEditConfig } from "./SeedEditConfig";

/**
 * Provider 配置枚举（预留扩展）
 */
export type ProviderConfig = { "type": "seed-edit" } & SeedEditConfig;
