// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 火山引擎 SeedEdit 配置
 */
export type SeedEditConfig = { 
/**
 * API Key
 */
apiKey: string, 
/**
 * 模型 ID
 */
model: string, };
